Mensagens:
  VIP: '&4&l[PDGH] &6&lVoce e um jogador VIP e consegue criar placas coloridas. Veja as cores com /cores'
  NVIP: '&4&l[PDGH] &cVoce nao e um jogador VIP e nao consegue criar placas coloridas. Veja as cores VIP com /cores'